### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by clawnotfound** [gyhdog99/MoCLE#1]
Thank for your great work! but i wonder when can you release your code, thx

**Comment by supertyd** [comment]
+1 ，nice job ，but code

**Comment by lyt719** [comment]
+1 ，nice job ，but code

**Comment by iamjinchen** [comment]
+1， clustering is a good idea, code, please

**Comment by KaiChen1998** [comment]
@clawnotfound @supertyd @lyt719 @iamjinchen Thank you for your great interest and patience in MoCLE! We have released the inference code and several checkpoints of the initial version MoCLE. Welcome to the check and use!
