### ISSUE TITLE
Conv Layer Initialization error

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [gyhdog99/MoCLE#2]
Dear authors, thanks for the great work! I am trying to use your MoELoRA layers, however, I encounter the following initilization error and could not solve it.

  File "/home/jchenhu/code/C2-RV/code/models/lora.py", line 397, in __init__
    self._init_empty_weights(nn.Conv3d, in_channels, out_channels, kernel_size, stride, padding)
  File "/home/jchenhu/code/C2-RV/code/models/lora.py", line 46, in _init_empty_weights
    cls.__init__(self, *args, device="meta", **kwargs)
  File "/home/jchenhu/anaconda3/envs/DIF-Net/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 591, in __init__
    super(Conv3d, self).__init__(
  File "/home/jchenhu/anaconda3/envs/DIF-Net/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 86, in __init__
    super(_ConvNd, self).__init__()
TypeError: __init__() missing 2 required positional arguments: 'in_features' and 'out_features'

**Comment by Capricious-Liu** [comment]
Could you let me know if you followed the instructions to set up MoCLE, and pls provide the complete log.
Btw, it could be caused by the different version of peft. Our code is based on peft-0.6.0.dev0.
You can install the peft with our defined package following [this](https://github.com/gyhdog99/MoCLE/tree/main?tab=readme-ov-file#installation).

**Comment by JixiangChen-Jimmy** [comment]
Thanks for your prompt response, I have addressed this issue.
However, I have some questions about the 'multiple_lora' and 'num_experts' settings. According to your code in https://github.com/gyhdog99/MoCLE/blob/eae3744e4ed9dd703112abc28ae4ebb5c91324f3/peft-main/src/peft/tuners/lora/layer.py#L220
It seems that each time calling the update_layer function will register a lora layer (a expert), but I can not find where you register multiple lora layers based on the 'num_experts', could you kindly provide more instructions?

**Comment by gyhdog99** [comment]
> Thanks for your prompt response, I have addressed this issue. However, I have some questions about the 'multiple_lora' and 'num_experts' settings. According to your code in
> 
> https://github.com/gyhdog99/MoCLE/blob/eae3744e4ed9dd703112abc28ae4ebb5c91324f3/peft-main/src/peft/tuners/lora/layer.py#L220
> 
> 
> It seems that each time calling the update_layer function will register a lora layer (a expert), but I can not find where you register multiple lora layers based on the 'num_experts', could you kindly provide more instructions?

Hi,

It's in line 154-158 of mocle.py

**Comment by JixiangChen-Jimmy** [comment]
Thanks for your help!
